### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by fvonschrenk** [s9tpepper/MongoAS3#3]
db.person.find({ firstname : { $regex : /ra/i} });  is running

doc1.put("$regex","/ra/i");
doc.put("firstname",doc1);

xxxx.collection("person").find(doc).add(onCursorReady); is not running. Any Idee

**Comment by s9tpepper** [comment]
Hm, I'm not sure about this one, fvonschrenk. I'm going to run some tests and look up in the BSON documentation to make sure regular expressions are being handled correctly. I haven't tried using regular expressions with MongoAS3 yet.

**Comment by fvonschrenk** [comment]
Hallo Omar,

thanks for the Answer.

This Sample is working

db.person.find({firstname : { $ne : "Frank" }});

doc1.put("$ne","Frank");
doc.put("firstname",doc1);
 dm.db.collection("person").find(doc).add(onCursorReady);

So that means Advanced Queries could run.
I'll make some tests too. Especially for Advanced Queries.

Advanced Queries
Aggregation
and Sorting are Important.

Actually I'm study your programmcode and the Java driver.
So I hope I can help to improve mongoas3.

Regards

Frank

2011/10/7 Omar Gonzalez <
reply@reply.github.com>

**Comment by fvonschrenk** [comment]
A small report. Just writing unit tests for the Extended query. 
Current went through the following conditional operator test.

pass  $gt
pass  $lt
pass  $gte
pass  $lte
pass  $all
pass  $nin

**Comment by s9tpepper** [comment]
Thanks for the info Frank! I've been using advanced queries myself and had not run into any issues, my guess is that BSON is expecting me to encode a regular expression slightly different than a String object and so perhaps that's where its getting confused. I'm going to have some time over the weekend to investigate this further.

I used the C# driver to find portions of code that I wasn't understanding from just reading the MongoDB driver specs because the C# driver is the cleanest source code I found amongst the other drivers. I'll have to peek in there and see if there's any special handling for regular expressions. In fact, I'm about 99.999% positive the error is in the BSON library. I didn't actually code that part from scratch, I took it from ActionMongo (which is abandoned and not nearly as functional as MongoAS3). Looking at the BSON spec (http://bsonspec.org/#/specification) I see they do expect a special handling for regular expression. I can likely add this in this weekend. Thanks again for the report!
