### ISSUE TITLE
Connection failed ...

### ISSUE THREAD

**Issue by jforatier** [s9tpepper/MongoAS3#7]
Hi,
I've tried your sample but i've got the "connection failed ..." message.

Is there a way to show an error message ?
Maybe you have some advice to configure server part ? I'm currently running an Virtual Machine with Ubuntu.

Thanks for your answer.

**Comment by s9tpepper** [comment]
Did you make sure that you set up a Socket Policy File Server? There is an example of a PHP one in the repository, but Flash requires you have such a policy file being served to allow connections to the socket port.

**Comment by pablolemosassis** [comment]
Hei, I am having the same problem.
I am doing an AIR app, so, like you said in your blog, it shouldnt be a problem:
"
If MongoAS3 is used in an AIR project then there is nothing additional to do because AIR applications do not check policy files for sockets.
"

Anyways, I did try with the Policy files with no success.
My MongoDB is perfectly running at the default port but I cant manage to access it with AS3.

I've tried all combinations, but is there something in the way we declare IP or domains?
Is there anything else to be customized at the php files besides $ip and $port?

I've tried: 

#AS3
mongo = new Mongo("http://my.IP.number", 27017);
#PHP
$ip = '[http://my.IP.number]';
$port = 843;  

or

#AS3
mongo = new Mongo("my.IP.number", 27017);
#PHP
$ip = '[my.IP.number]';
$port = 843;  

or 

#AS3
mongo = new Mongo("http://mydomain.com", 27017);
#PHP
$ip = '[http://mydomain.com]';
$port = 843;  

Thanks for the nice work.

**Comment by pablolemosassis** [comment]
SOLVED:

My server has a firewall, so I had to add this rule to the iptables:
 -A RH-Firewall-1-INPUT -p tcp -m tcp --dport 27017 -m comment --comment "Mongo" -j ACCEPT

No needs for socket files. 
Just:
#AS3
mongo = new Mongo("my.IP.number", 27017);
